// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistrawts.Module.Infrastructure;

#nullable disable

namespace CoopSystem.API.Migrations.SistrawtsDb
{
    [DbContext(typeof(SistrawtsDbContext))]
    [Migration("20260313121530_AddSubcategoriaToMetasAndResultados")]
    partial class AddSubcategoriaToMetasAndResultados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.CategoriaIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasIndicadores");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EhPercentual")
                        .HasColumnType("bit");

                    b.Property<string>("NomeMeta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("QuantoMaiorMelhor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Indicadores");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.IndicadorSubcategoria", b =>
                {
                    b.Property<int>("IndicadorId")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoriaId")
                        .HasColumnType("int");

                    b.HasKey("IndicadorId", "SubcategoriaId");

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("IndicadoresSubcategorias");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.MetaMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("IndicadorId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMeta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("IndicadorId", "SubcategoriaId", "Ano", "Mes")
                        .IsUnique()
                        .HasFilter("[SubcategoriaId] IS NOT NULL");

                    b.ToTable("MetasMensais");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.MicroAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoComprovacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PlanoAcaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrevisaoConclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Trativa")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("PlanoAcaoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("MicroAcoes");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.PlanoAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PercentualConclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("PrevisaoConclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Relatorio")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Trativa")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("PlanosAcao");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.ResultadoMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IndicadorId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorResultado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("IndicadorId", "SubcategoriaId", "Ano", "Mes")
                        .IsUnique()
                        .HasFilter("[SubcategoriaId] IS NOT NULL");

                    b.ToTable("ResultadosMensais");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.SubcategoriaIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("SubcategoriasIndicadores");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PermiteJuridico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PermiteSimuladorTaxa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PermiteSistrawts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.Indicador", b =>
                {
                    b.HasOne("Sistrawts.Module.Domain.Entities.CategoriaIndicador", "Categoria")
                        .WithMany("Indicadores")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.IndicadorSubcategoria", b =>
                {
                    b.HasOne("Sistrawts.Module.Domain.Entities.Indicador", "Indicador")
                        .WithMany("Subcategorias")
                        .HasForeignKey("IndicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistrawts.Module.Domain.Entities.SubcategoriaIndicador", "Subcategoria")
                        .WithMany("Indicadores")
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicador");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.MetaMensal", b =>
                {
                    b.HasOne("Sistrawts.Module.Domain.Entities.Indicador", "Indicador")
                        .WithMany("MetasMensais")
                        .HasForeignKey("IndicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistrawts.Module.Domain.Entities.SubcategoriaIndicador", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Indicador");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.MicroAcao", b =>
                {
                    b.HasOne("Sistrawts.Module.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany("MicroAcoesCriadas")
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistrawts.Module.Domain.Entities.PlanoAcao", "PlanoAcao")
                        .WithMany("MicroAcoes")
                        .HasForeignKey("PlanoAcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistrawts.Module.Domain.Entities.Usuario", "Responsavel")
                        .WithMany("MicroAcoesResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("PlanoAcao");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.PlanoAcao", b =>
                {
                    b.HasOne("Sistrawts.Module.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany("PlanosCriados")
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistrawts.Module.Domain.Entities.Usuario", "Responsavel")
                        .WithMany("PlanosResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.ResultadoMensal", b =>
                {
                    b.HasOne("Sistrawts.Module.Domain.Entities.Indicador", "Indicador")
                        .WithMany("ResultadosMensais")
                        .HasForeignKey("IndicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistrawts.Module.Domain.Entities.SubcategoriaIndicador", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Indicador");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.CategoriaIndicador", b =>
                {
                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.Indicador", b =>
                {
                    b.Navigation("MetasMensais");

                    b.Navigation("ResultadosMensais");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.PlanoAcao", b =>
                {
                    b.Navigation("MicroAcoes");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.SubcategoriaIndicador", b =>
                {
                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("Sistrawts.Module.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("MicroAcoesCriadas");

                    b.Navigation("MicroAcoesResponsavel");

                    b.Navigation("PlanosCriados");

                    b.Navigation("PlanosResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
